### PR TITLE
Remove topics notebooks

### PR DESCRIPTION
**Pull request by philippjfr**
Since the existing topics are now built on example.pyviz.org I've decided to remove them from the HoloViews repo.

Closes https://github.com/pyviz/holoviews/issues/1638

### CODE REVIEW

**Comment by jbednar** [comment]
Closing them seems fine, but it seems like they still ought to be linked from the hv docs.

**Comment by philippjfr** [comment]
Any suggestion on where?

**Comment by philippjfr** [comment]
The gallery I suppose.

**Comment by jbednar** [comment]
Our original idea with examples.pyviz.org is that it would serve as a place to capture and publish examples in a well-defined and stable location that could then be referenced by any project illustrated by that example.  So I assume they can just appear in the HoloViews gallery like any other HoloViews examples...

**Comment by philippjfr** [comment]
Okay, I'm going ahead with this PR. The topics aren't linked currently so adding them is a separate issue.

**Pull request merged**
