### PR TITLE
Add numpy logs to transformations

### PR DESCRIPTION
**Pull request by henriqueribeiro**
As title states, this PR adds logs function to the available transformations

### CODE REVIEW

**Comment by philippjfr** [comment]
One of the existing tests will need to be updated, otherwise this looks fine to me:

```
  File "/home/travis/build/pyviz/holoviews/holoviews/tests/util/testtransform.py", line 173, in test_ufunc_expression_repr
    self.assertEqual(repr(np.log(dim('float'))), "np.log(dim('float'))")
  File "/home/travis/build/pyviz/holoviews/holoviews/element/comparison.py", line 79, in assertEqual
    asserter(first, second)
  File "/home/travis/build/pyviz/holoviews/holoviews/element/comparison.py", line 56, in simple_equality
    raise cls.failureException(msg or standardMsg)
AssertionError: "dim('float').log()" != "np.log(dim('float'))"
```

**Comment by philippjfr** [comment]
Thanks a lot for contributing!

**Comment by henriqueribeiro** [comment]
Just fixed the test @philippjfr

**Comment by jlstevens** [comment]
Thanks for the PR @henriqueribeiro!

**Pull request merged**
