### PR TITLE
Add `visible` style option for simple plotly/bokeh plots.

### PR DESCRIPTION
**Pull request by jonmmease**
Setting `visible` to `False` will fully hide the individual element trace.

This option is very useful for the linked selection effort...

### CODE REVIEW

**Comment by jbednar** [comment]
Is there a chance to unify this API with Bokeh?

**Comment by jonmmease** [comment]
> Is there a chance to unify this API with Bokeh?

I'm not sure. Does anyone know if Bokeh plot elements have an equivalent property to hide everything?  For the selection work I'm using the `opacity` style options to do this.

**Comment by jbednar** [comment]
I'm not an expert at it, but Bokeh has a variety of related options like muted_alpha, muted_color, selection_glyph.visible, nonselection_glyph.visible, and so on; @philippjfr may be able to chat about it on Monday at see where things line up between the two backends.

**Comment by philippjfr** [comment]
>I'm not sure. Does anyone know if Bokeh plot elements have an equivalent property to hide everything?

Most bokeh elements indeed have a visible property and we should expose it.

**Comment by jonmmease** [comment]
> Most bokeh elements indeed have a visible property and we should expose it.

Ok, thanks. I'll take a look

**Comment by jonmmease** [comment]
Alright, I added the `visible` style property to all of the simple (non-composite) Bokeh element plots.  Basically, for all of the cases where all that is needed is to pass the property along to the single Bokeh glyph representing the element.  I didn't do anything with the composite Bokeh elements to this point, as these will take some actual logic changes.

Sound alright for now?

**Comment by philippjfr** [comment]
>Sound alright for now?

Yes, absolutely.

**Comment by jbednar** [comment]
Great!

**Pull request merged**
