### PR TITLE
Add clabel param

### PR DESCRIPTION
**Pull request by ahuang11**
image
image

### CODE REVIEW

**Comment by philippjfr** [comment]
Will merge this after the layout PR goes in.

**Comment by jlstevens** [comment]
Now layout is merged, I'm happy to see this go in once the merge conflicts are resolved. My only question is whether `clabel` is the standard name for this (it makes sense to me, just checking we shouldn't be considering some other name....)

**Comment by jlstevens** [comment]
@philippjfr Looks like the merge conflicts are resolved and the tests are passing. If you are happy with the `clabel` name, I am happy if you want to go ahead and merge this PR.

**Comment by philippjfr** [comment]
I'm happy with it.

**Comment by jlstevens** [comment]
Ok, merging then!

**Pull request merged**
