### PR TITLE
Preprocessor improvements

### PR DESCRIPTION
**Pull request by jlstevens**
This PR aims to improve the nbconvert preprocessors from notebook to vanilla Python. This will make it easier to use notebooks together with bokeh server.

### CODE REVIEW

**Comment by philippjfr** [comment]
Ready to merge or are you still working on this?

**Comment by jlstevens** [comment]
There are a number of things I would like to get into this PR before merging. I'll ping you once I think it is ready.

**Comment by philippjfr** [comment]
@jlstevens How does this relate to the preprocessing now in bokeh?

**Comment by jlstevens** [comment]
This PR can now be closed: HoloViews no longer relies on (or recommends) using the old HoloViews magics and Bokeh now strips out all other magics it finds.

That said, I do have one task to remove [this code](https://github.com/pyviz/holoviews/blob/master/holoviews/util/command.py#L60) but I'll do that separately and close this PR.

**Pull request closed without merging**
