### PR TITLE
GitHub URL updates

### PR DESCRIPTION
**Pull request by philippjfr**

### CODE REVIEW

**Comment by jlstevens** [comment]
Thanks! Looks like the test errors are transients?

**Comment by philippjfr** [comment]
Seems like a ton of transients, will have to investigate.

**Comment by philippjfr** [comment]
Transients seem to have gone away but that was a worrying streak of failures.

**Comment by philippjfr** [comment]
I'll just go ahead and merge.

**Comment by jlstevens** [comment]
> Transients seem to have gone away but that was a worrying streak of failures.

Worrying indeed. This PR isn't touching code so I'll go and merge.

**Comment by philippjfr** [comment]
>This PR isn't touching code so I'll go and merge.

It's already merged.

**Pull request merged**
