### PR TITLE
Unpin IPython and disable jedi completion by default

### PR DESCRIPTION
**Pull request by philippjfr**
Not supporting newer versions of IPython is really not feasible in the long run, so I've made the holoviews extension disable jedi tab-completion in IPython, if someone really wants jedi completion they can toggle it with ``hv.extension(allow_jedi_completion=True)``.

Fixes https://github.com/pyviz/holoviews/issues/3540

@jlstevens @jbednar Thoughts on this appreciated, users were getting offered old versions of holoviews by conda because conda prefers to install an old version of a new package rather than downgrade the version of an existing package.

### CODE REVIEW

**Comment by jlstevens** [comment]
Seems reasonable. Of course, I would prefer it if IPython weren't always broken.

**Comment by philippjfr** [comment]
>I assume there is no prospect of this being fixed at that end...

It's a jedi issue I imagine so should probably be fixed there. It's certainly not getting fixed before hv 1.12.0 though, so for the time being I think this is the best we can do.

**Comment by jlstevens** [comment]
Ok. I'll merge when the tests pass.

**Comment by philippjfr** [comment]
@jlstevens Ready to merge.

**Comment by stonebig** [comment]
new release is still planned for this week ?

**Comment by philippjfr** [comment]
>new release is still planned for this week ?

@stonebig Hoping that's the case, waiting on bokeh though and I don't have direct control over that. It's certainly getting very close though.

**Pull request merged**
