### PR TITLE
Consistently renamed to PyViz global object

### PR DESCRIPTION
**Pull request by philippjfr**
Completes the renaming from the HoloViews global object to PyViz.

Linked to https://github.com/pyviz/pyviz_comms/pull/24

### CODE REVIEW

**Comment by fmaussion** [comment]
not directly related: is the hv repository also going to move to the pyviz organization eventually?

**Comment by philippjfr** [comment]
>not directly related: is the hv repository also going to move to the pyviz organization eventually?

Yes, that's long overdue. The plan was to split out the plotting components into their own repos (holoviews-bokeh, holoviews-matplotlib, holoviews-plotly) and then migrate everything across to pyviz.

**Comment by jbednar** [comment]
I don't see why not move them first and be done with the move before having to worry about the split.

**Comment by philippjfr** [comment]
>I don't see why not move them first and be done with the move before having to worry about the split.

I agree.

**Comment by philippjfr** [comment]
The main annoyance will be updating various parts of our build and test infrastructure.

**Pull request closed without merging**
